FROM golang:1.22-alpine AS builder

RUN apk update && apk add --no-cache git && apk add --no-cach bash && apk add build-base

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o main cmd/main.go

FROM alpine:latest AS runner

COPY --from=builder /app/main .

COPY .env .

ENV DB_HOST=127.0.0.1
ENV DB_PORT=5432
ENV DB_USER=postgres
ENV DB_PASSWORD=password
ENV DB_NAME=go_blog_platform

EXPOSE 8080

CMD ["./main"]